export enum Decision {
  WARNING = 'WARNING',
  CLOSURE_IMMEDIATE = 'CLOSURE_IMMEDIATE',
  CLOSURE_DEADLINE = 'CLOSURE_DEADLINE',
  PROSECUTION_RECOMMENDED = 'PROSECUTION_RECOMMENDED',
  NO_ACTION = 'NO_ACTION',
}
